services:
  app:
    build: .
    links:
      - db
    ports:
      - "80:80"
    environment:
      - FLASK_KEY=${FLASK_KEY}
      - DB_URL=${DB_URL}
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - __pycache__/
            - secrets/
            - .git/
            - .gitignore
            - .vscode/
            - .idea/
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5433:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:  
  db-password:
    file: secrets/password.txt 
