"""add is_active to documents in order to logic elimination

Revision ID: 22ef1efa9db8
Revises: 82b9cf8c405b
Create Date: 2024-03-13 14:03:55.336307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef1efa9db8'
down_revision = '82b9cf8c405b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
